language: c
 
install:
  - sudo apt-get install mono-devel mono-gmcs
  - chmod +x lib/xunit/xunit.console.clr4.x86.exe
 
script:
  - xbuild Factory.build
  - ./xunit/xunit.console.clr4.x86.exe ./bin/debug/RSG.Factory.Tests.dll